import type { WorkplaceStatus } from '@/lib/workplace-types';

export const defaultStatus: WorkplaceStatus = {
  lastHeartbeat: '',
  frentes: {
    tesis: {
      nombre: 'Tesis',
      estado: 'verde',
      ultimoAvance: 'Tema y línea de trabajo definidos',
      fechaAvance: '2026-04-26 15:04',
      proximaTarea: 'Recibir proyecto de tesis y pasar a operacionalización de variables',
      necesitaDelUsuario: 'Enviar archivo del proyecto de tesis',
      extra: 'Frente activo. Objetivo: dejar sistema de variables y recolección intraoperatoria listo.',
    },
    papers: {
      nombre: 'Papers',
      estado: 'verde',
      ultimoAvance: 'Prioridad de research definida',
      fechaAvance: '2026-04-26 15:04',
      proximaTarea: 'Armar estructura autónoma para ejecutar ideas y casos',
      necesitaDelUsuario: '',
      extra: 'Frente activo. Objetivo: convertir ideas clínicas en pipeline real de papers.',
    },
    obras: {
      nombre: 'Obras',
      estado: 'amarillo',
      ultimoAvance: 'Seguimiento operativo pendiente de consolidación',
      fechaAvance: '2026-04-26 15:04',
      proximaTarea: 'Ordenar control de costos, avances y reportes por obra',
      necesitaDelUsuario: '',
      extra: 'Incluye Costa Verde, Gandini y Brasil.',
    },
    flipping: {
      nombre: 'Flipping inmobiliario',
      estado: 'verde',
      ultimoAvance: 'Criterio de búsqueda y margen objetivo definidos',
      fechaAvance: '2026-04-26 15:04',
      proximaTarea: 'Mantener shortlist y validar oportunidades con costo de reforma',
      necesitaDelUsuario: '',
      extra: 'Objetivo mínimo: 20% anual en dólares.',
    },
    reels: {
      nombre: 'Reels y contenido',
      estado: 'verde',
      ultimoAvance: 'Sistema de reel diario activo como prioridad',
      fechaAvance: '2026-04-26 15:04',
      proximaTarea: 'Sostener producción diaria y mejora continua',
      necesitaDelUsuario: '',
      extra: 'Frente activo de posicionamiento profesional.',
    },
    crm: {
      nombre: 'CRM derivadores',
      estado: 'amarillo',
      ultimoAvance: 'Prioridad definida para los próximos 30 días',
      fechaAvance: '2026-04-26 15:04',
      proximaTarea: 'Diseñar estructura simple para registrar derivaciones y seguimiento',
      necesitaDelUsuario: '',
      extra: 'Objetivo: saber quién deriva, cuánto y qué seguimiento requiere.',
    },
  },
};
