export const PILAR_CATEGORY_OPTIONS = [
  'Ventas Maxi Pisos',
  'Ventas Mozzetto',
  'Ventas Flex-Color',
  'Ventas Lamparas',
  'Ventas Mobile',
  'Ventas Muresco',
  'Ventas Otros',
  'Maxi Pisos - Pagos',
  'Mozzetto - Pagos',
  'Flex-Color - Pagos',
  'Lamparas - Pagos',
  'Mobile - Pagos',
  'Muresco - Pagos',
  'Otros Proveedores - Pagos',
  'Impuestos',
  'Viaticos/Combustible',
  'Ferreteria',
  'Publicidad',
  'Alquiler',
  'Colocación',
  'Servicios',
  'Fletes',
  'Gastos Generales',
  'Contador',
  'AFIP',
  'Showroom',
  'Compra Dolares',
  'Utilidades Pilar',
  'Utilidades Male',
] as const;
