from pathlib import Path

p = Path('/Users/jarvis/workplace-app/src/components/dashboard-client.tsx')
text = p.read_text()
text = text.replace("  useEffect(() => {\n    const interval = window.setInterval(async () => {\n      const res = await fetch('/api/status');\n      const next = await res.json();\n      setStatus(next);\n    }, 15000);\n    return () => window.clearInterval(interval);\n  }, []);\n", "  useEffect(() => {\n    const interval = window.setInterval(async () => {\n      try {\n        const res = await fetch('/api/status');\n        if (!res.ok) return;\n        const next = await res.json();\n        setStatus(next);\n      } catch {}\n    }, 15000);\n    return () => window.clearInterval(interval);\n  }, []);\n")
text = text.replace("  async function sendMessage() {\n    if (!message.trim()) return;\n    await fetch('/api/message', {\n      method: 'POST',\n      headers: { 'Content-Type': 'application/json' },\n      body: JSON.stringify({ message: message.trim() }),\n    });\n    setMessage('');\n  }\n", "  async function sendMessage() {\n    if (!message.trim()) return;\n    try {\n      const res = await fetch('/api/message', {\n        method: 'POST',\n        headers: { 'Content-Type': 'application/json' },\n        body: JSON.stringify({ message: message.trim() }),\n      });\n      if (!res.ok) {\n        alert('Mensajería no disponible en este deploy.');\n        return;\n      }\n      setMessage('');\n    } catch {\n      alert('Mensajería no disponible en este deploy.');\n    }\n  }\n")
text = text.replace("  async function addTask(frente: string) {\n    const tarea = taskInputs[frente]?.trim();\n    if (!tarea) return;\n    await fetch('/api/task', {\n      method: 'POST',\n      headers: { 'Content-Type': 'application/json' },\n      body: JSON.stringify({ frente, tarea }),\n    });\n    setTaskInputs((prev) => ({ ...prev, [frente]: '' }));\n    setOpenTask(null);\n  }\n", "  async function addTask(frente: string) {\n    const tarea = taskInputs[frente]?.trim();\n    if (!tarea) return;\n    try {\n      const res = await fetch('/api/task', {\n        method: 'POST',\n        headers: { 'Content-Type': 'application/json' },\n        body: JSON.stringify({ frente, tarea }),\n      });\n      if (!res.ok) {\n        alert('Alta de tareas no disponible en este deploy.');\n        return;\n      }\n      setTaskInputs((prev) => ({ ...prev, [frente]: '' }));\n      setOpenTask(null);\n    } catch {\n      alert('Alta de tareas no disponible en este deploy.');\n    }\n  }\n")
text = text.replace("  async function forceHeartbeat() {\n    await fetch('/api/heartbeat', { method: 'POST' });\n    const res = await fetch('/api/status');\n    setStatus(await res.json());\n  }\n", "  async function forceHeartbeat() {\n    try {\n      const beat = await fetch('/api/heartbeat', { method: 'POST' });\n      if (!beat.ok) {\n        alert('Heartbeat remoto no disponible en este deploy.');\n        return;\n      }\n      const res = await fetch('/api/status');\n      if (!res.ok) return;\n      setStatus(await res.json());\n    } catch {\n      alert('Heartbeat remoto no disponible en este deploy.');\n    }\n  }\n")
text = text.replace("  async function viewDetail(frente: string) {\n    const res = await fetch(`/api/detail?frente=${encodeURIComponent(frente)}`);\n    const data = await res.json();\n    alert(data.file || 'No encontré un archivo para este frente todavía.');\n  }\n", "  async function viewDetail(frente: string) {\n    try {\n      const res = await fetch(`/api/detail?frente=${encodeURIComponent(frente)}`);\n      if (!res.ok) {\n        alert('Detalle local no disponible en este deploy.');\n        return;\n      }\n      const data = await res.json();\n      alert(data.file || 'No encontré un archivo para este frente todavía.');\n    } catch {\n      alert('Detalle local no disponible en este deploy.');\n    }\n  }\n")
p.write_text(text)
